############################################################################
#
# netutils/iptlite/Makefile
# iptlite networking application
#
############################################################################

include $(APPDIR)/Make.defs

# built-in application info

MODULE    = $(CONFIG_NETUTILS_IPTLITE)
PROGNAME  = $(CONFIG_NETUTILS_IPTLITE_PROGNAME)
PRIORITY  = $(CONFIG_NETUTILS_IPTLITE_PRIORITY)
STACKSIZE = $(CONFIG_NETUTILS_IPTLITE_STACKSIZE)

# Example

MAINSRC = iptlite.c

include $(APPDIR)/Application.mk
